import type { Metadata } from 'next'
import Link from 'next/link'
import { Geist, Geist_Mono } from 'next/font/google'

import { getPages } from '@/sanity/sanity-utils'
import '@/app/globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'My Awesome Site',
	description: 'Generated by Next + Sanity',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const pages = await getPages()

	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-3xl mx-auto py-10`}
			>
				<header>
					<nav className='flex items-center justify-between'>
						<Link
							href='/'
							className='bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold'
						>
							Eliahu
						</Link>

						<div className='flex items-center gap-3 text-sm text-gray-300'>
							{pages.map(page => (
								<Link
									key={page._id}
									href={`/${page.slug}`}
									className='hover:underline hover:text-white transition-colors'
								>
									{page.title}
								</Link>
							))}
						</div>
					</nav>
				</header>
				<main className='py-20'>{children}</main>
			</body>
		</html>
	)
}
